from .random_sampling import RandomSampling
from .least_confidence import LeastConfidence
from .margin_sampling import MarginSampling
from .entropy_sampling import EntropySampling
from .gan_sampling import ganSampling
from .least_confidence_dropout import LeastConfidenceDropout
from .margin_sampling_dropout import MarginSamplingDropout
from .entropy_sampling_dropout import EntropySamplingDropout
from .kmeans_sampling import KMeansSampling
from .kcenter_greedy import KCenterGreedy
from .bayesian_active_learning_disagreement_dropout import BALDDropout
from .core_set import CoreSet
from .adversarial_bim import AdversarialBIM
from .adversarial_deepfool import AdversarialDeepFool
from .active_learning_by_learning import ActiveLearningByLearning
from .badge_sampling  import BadgeSampling
from .baseline_sampling  import BaselineSampling
from .isal_sampling import ISAL_Sampling
from .cm_sampling import CMSampling
from .fm_sampling import FMSampling
from .random_sampling1d import RandomSampling1d
from .margin_sampling1d import MarginSampling1d
from .badge_sampling1d import BadgeSampling1d
from .cm_sampling1d import CMSampling1d
from .fm_sampling1d import FMSampling1d
from .random_sampling_poor import RandomSampling_poor